package de.kluge.common;

public enum Priority {
	IMPORTEND_URGENT_1, IMPORTEND_URGENT_2, IMPORTEND_URGENT_3, IMPORTEND_NOT_URGENT_1, IMPORTEND_NOT_URGENT_2, IMPORTEND_NOT_URGENT_3, NOT_IMPORTEND_URGENT_1, NOT_IMPORTEND_URGENT_2, NOT_IMPORTEND_URGENT_3, NOT_IMPORTEND_NOT_URGENT_1, NOT_IMPORTEND_NOT_URGENT_2, NOT_IMPORTEND_NOT_URGENT_3
}